name: stock_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  intl: ^0.19.0
  multi_dropdown: ^2.1.4
  riverpod_annotation: ^2.3.4
  syncfusion_flutter_charts: ^24.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
